Add tab key support
Juicy/juicy-checkbox-group pull request #4
Opened 2017-03-28 13:02 UTC by aloscha

2017-03-31 17:11 UTC, warpech requested changes

2017-03-31 17:11 UTC, warpech commented on juicy-checkbox-group-item.html
> +                    <div id="checkboxItem" data-checkable$="{{checkable}}" data-checked$="{{checked}}" on-click="toggleCheckbox" on-keypress="keypressCheckbox" tabindex="0">
Normally such things are done with `change` event. Have you tried that?

We even do it in KitchenSink: https://github.com/StarcounterApps/KitchenSink/blob/master/src/KitchenSink/wwwroot/KitchenSink/CheckboxPage.html#L7

2017-04-10 12:17 UTC, warpech commented
ping @aloscha, @mmnosek, where are we with this?

2017-04-10 13:51 UTC, aloscha commented on juicy-checkbox-group-item.html
> +                    <div id="checkboxItem" data-checkable$="{{checkable}}" data-checked$="{{checked}}" on-click="toggleCheckbox" on-keypress="keypressCheckbox" tabindex="0">
Difference between KichetnSink and JuicyCheckboxItem is that in KitchenSink we have `input`, in juicy we have `div`

2017-04-10 14:01 UTC, warpech commented on juicy-checkbox-group-item.html
> +                    <div id="checkboxItem" data-checkable$="{{checkable}}" data-checked$="{{checked}}" on-click="toggleCheckbox" on-keypress="keypressCheckbox" tabindex="0">
Ah, I did not expect that.

Anyway, `keypress` is a strange event. See: https://www.kirupa.com/html5/keyboard_events_in_javascript.htm

Please check if you could use `keydown` or `keyup`, that would be preferable.

2017-04-10 14:02 UTC, aloscha commented on juicy-checkbox-group-item.html
> +                    <div id="checkboxItem" data-checkable$="{{checkable}}" data-checked$="{{checked}}" on-click="toggleCheckbox" on-keypress="keypressCheckbox" tabindex="0">
I think `keyup` will be enough. Thanks

2017-05-05 11:08 UTC, mmnosek commented
@warpech I've changed keypress to keydown as you asked for.

2017-05-05 11:08 UTC, mmnosek approved these changes

2017-05-05 12:25 UTC, warpech approved these changes
Looks good! @mmnosek will you merge?

2017-05-05 12:25 UTC, merged